# Generated by Django 3.2.5 on 2021-07-18 09:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_address_zip"),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO store_collection (title)
            VALUES ('collection1')
            """,
            """
            DELETE FROM store_collection
            WHERE title='collection1'
            """,
        )
    ]
