version: "3.9"

services:
  mysql:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: StrongPassword(?)
      MYSQL_DATABASE: storefront
      MYSQL_USER: storefront
      MYSQL_PASSWORD: StrongPassword(?)
    ports:
    - "3306:3306"
volumes:
  db_data: { }